services:
  - type: web
    name: SmartClient
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT SmartClient.asgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "SmartClient.onrender.com"
      - key: DB_NAME
        fromDatabase: true
      - key: DB_USER
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true
      - key: DB_HOST
        fromDatabase: true
      - key: DB_PORT
        fromDatabase: true

    staticPublishPath: staticfiles  # <--- Render servirá archivos desde aquí
    staticPublishUrl: /static       # <--- Rutas como /static/admin/ funcionarán